# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Raging Rooster REM
#tagline:            
description:         TL;DR Malware Analysis
url:                 https://ragingrooster.github.io
baseurl:             ''
plugins:              [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Raging Rooster
  url:               https://ragingrooster.github.io
  email:             ragingroosterrem@gmail.com

# Custom vars
version:             1.0.0
